# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 426d97aa2285c70100df2fc3e215f3d3fed3a6d4b8d58d58f061e20d692a86cbdf99fa1858019e43d933ffd7af6dfa1c4937acab1bd737b6f0967f2218e3ce3b

test:
  secret_key_base: 095a4b8e3d548c606b7b8fd35b194e67be684e32679a5fab6c68f4ecc7f58738cb43babb954a55f04637271a9eaf2869d7ce9f4ebda22666512c16c9e550bb11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
